// flow-typed signature: 288ca51fc0d172fa78b715efde443fd7
// flow-typed version: <<STUB>>/eslint-config-with-prettier_v^5.0.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-with-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-with-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-with-prettier/jest.setup' {
  declare module.exports: any;
}

declare module 'eslint-config-with-prettier/src/eslintrc.test' {
  declare module.exports: any;
}

declare module 'eslint-config-with-prettier/src/test-markup' {
  declare module.exports: any;
}

declare module 'eslint-config-with-prettier/src/test-markup.output' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-with-prettier/jest.setup.js' {
  declare module.exports: $Exports<'eslint-config-with-prettier/jest.setup'>;
}
declare module 'eslint-config-with-prettier/src/eslintrc.test.js' {
  declare module.exports: $Exports<'eslint-config-with-prettier/src/eslintrc.test'>;
}
declare module 'eslint-config-with-prettier/src/test-markup.js' {
  declare module.exports: $Exports<'eslint-config-with-prettier/src/test-markup'>;
}
declare module 'eslint-config-with-prettier/src/test-markup.output.js' {
  declare module.exports: $Exports<'eslint-config-with-prettier/src/test-markup.output'>;
}
