version: 2
jobs:
  build:
    branches:
      only: master
    working_directory: ~/app
    docker:
    - image: circleci/node:10

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run:
        name: yarn
        command: yarn

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: CI
        command: make ci

    - run:
        name: Build
        command: make build

    - run:
        name: Docker Build
        command: |
          docker build -t ${PROJECT_NAME} .
          docker tag ${PROJECT_NAME} docker.io/eirwin/${PROJECT_NAME}:${CIRCLE_SHA1}
          docker login -u ${DOCKER_LOGIN_USERNAME} --password-stdin ${DOCKER_LOGIN_PASSWORD}
          docker push docker.io/eirwin/${PROJECT_NAME}:${CIRCLE_SHA1}
