version: 2
jobs:
  build:
    branches:
      only: master
    working_directory: ~/app
    docker:
    - image: circleci/node:10

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run:
        name: yarn
        command: yarn

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: ci
        command: make ci

    - run:
        name: build
        command: make build

#    - run:
#        name: deploy-web
#        command: ssh -o "StrictHostKeyChecking no" $DROPLET_USER@$DROPLET_IP 'cd /opt/chrisdriscol && eval `ssh-agent -s` && ssh-add ~/.ssh/github_rsa && git fetch origin && git reset --hard origin/master && make docker-web'
#
#    - run:
#        name: prune
#        command: ssh -o "StrictHostKeyChecking no" $DROPLET_USER@$DROPLET_IP 'docker system prune -f'


