version: 2
jobs:
  build:
    branches:
      only: master
    working_directory: ~/app
    docker:
    - image: circleci/node:10

    steps:
    - checkout
    - setup_remote_docker

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run:
        name: yarn
        command: yarn

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: CI
        command: make ci

    - run:
        name: Build
        command: make build

    - run:
        name: Docker Build
        command: |
          docker build -t ericirwin.io .
          docker tag ericirwin.io docker.io/eirwin/ericirwin.io:$CIRCLE_SHA1
          docker tag ericirwin.io docker.io/eirwin/ericirwin.io:latest
          docker login -u $DOCKER_LOGIN_USERNAME --password $DOCKER_LOGIN_PASSWORD
          docker push docker.io/eirwin/ericirwin.io:$CIRCLE_SHA1
          docker push docker.io/eirwin/ericirwin.io:latest
