version: 2
jobs:
  build:
    branches:
      only: master
    working_directory: ~/app
    docker:
    - image: circleci/node:10

    steps:
    - checkout
    - setup_remote_docker

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run:
        name: yarn
        command: yarn

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: CI
        command: make ci

    - run:
        name: Build
        command: make build

    - run:
        name: Install kubectl
        command: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $DIGITAL_OCEAN_API_TOKEN" "https://api.digitalocean.com/v2/kubernetes/clusters/ed504aa4-c702-476d-95f2-4f828fcade4a/kubeconfig" > kubeconfig
          mkdir -p $HOME/.kube && cp kubeconfig $HOME/.kube/config
          kubectl version

    - run:
        name: Docker Build & Push
        command: |
          docker build -t $CIRCLE_PROJECT_REPONAME .
          docker tag $CIRCLE_PROJECT_REPONAME docker.io/eirwin/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
          docker tag $CIRCLE_PROJECT_REPONAME docker.io/eirwin/$CIRCLE_PROJECT_REPONAME:latest
          docker login -u $DOCKER_LOGIN_USERNAME --password $DOCKER_LOGIN_PASSWORD
          docker push docker.io/eirwin/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
          docker push docker.io/eirwin/$CIRCLE_PROJECT_REPONAME:latest

    - run:
        name: Deploy
        command: |
          kubectl replace --force -Rf k8s/

